current_id: 0
last_id: 196357
timeout: 5
names:
  178608: "Mathtrade 19"
  180671: "Mathtrade 19.5"
  185291: "Mathtrade 20"
  187035: "Mathtrade 20.5"
  190207: "Mathtrade 21"
  191665: "Mathtrade 21.5"
  196357: "Mathtrade 22"
  178867: "Mathtrade testlist"
results:
  #178608: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2319%20-%20Wyniki.txt"
  #180671: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2319,5%20-%20Wyniki.txt"
  185291: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2320%20-%20Wyniki.txt"
  187035: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2320%2C5%20-%20Wyniki%20koncowe.txt"
  190207: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2321%20-%20Wyniki%20koncowe.txt"
  191665: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2321,5%20-%20Wyniki%20koncowe.txt"
  196357: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2322%20-%20Wyniki%20koncowe.txt"
lists:
  #178608: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2319%20-%20Listy.txt"
  #180671: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2319,5%20-%20Listy.txt"
  185291: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2320%20-%20Listy.txt"
  187035: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2320%2C5%20-%20Listy.txt"
  190207: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2321%20-%20Listy.txt"
  191665: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2321,5%20-%20Listy.txt"
  196357: "https://dl.dropboxusercontent.com/u/17622107/MatHandel%20%2322%20-%20Listy.txt"
url:
  development: "http://localhost:9292/"
  test: "http://localhost:9292/"
  production: "http://mathtrade.mgpm.pl/"